import type { SpriteDef } from '../ui/PixelSprite';
import * as S from './sprites';

export const SPRITES = {
  asker: S.SOLDIER,
  askerAdim: S.ASKER_ADIM,
  askerAdimSol: S.ASKER_ADIM_SOL,
  askerAdimSag: S.ASKER_ADIM_SAG,
  askerArka: S.ASKER_ARKA,
  askerArkaSol: S.ASKER_ARKA_SOL,
  askerArkaSag: S.ASKER_ARKA_SAG,
  sivil: S.SIVIL,
  sivilAdimSol: S.SIVIL_ADIM_SOL,
  sivilAdimSag: S.SIVIL_ADIM_SAG,
  sivilArka: S.SIVIL_ARKA,
  sivilArkaSol: S.SIVIL_ARKA_SOL,
  sivilArkaSag: S.SIVIL_ARKA_SAG,
  bank: S.BANK,
  oturanAsker: S.OTURAN_ASKER,
  oturanEmre: S.OTURAN_EMRE,
  oturanTolga: S.OTURAN_TOLGA,
  oturanSerkan: S.OTURAN_SERKAN,
  kantinBina: S.KANTIN_BINA,
  bayrak: S.BAYRAK_DIREGI,
  revir: S.REVIR,
  dolapSirasi: S.DOLAP_SIRASI,
  tepsiBandi: S.TEPSI_BANDI,
  pencere: S.PENCERE,
  askerSirt: S.ASKER_SIRT,
  yemekhaneMasa: S.YEMEKHANE_MASA,
  hedefTahtasi: S.HEDEF_TAHTASI,
  engel: S.ENGEL,
  ankesor: S.ANKESOR,
  agac: S.AGAC,
  askerEmre: S.ASKER_EMRE,
  askerTolga: S.ASKER_TOLGA,
  askerSerkan: S.ASKER_SERKAN,
  cavus: S.SERGEANT,
  ranzaDaginik: S.BUNK_MESSY,
  ranzaToplu: S.BUNK_TIDY,
  tufek: S.RIFLE,
  tepsi: S.TRAY,
  postal: S.BOOT,
  gunes: S.SUN,
  ay: S.MOON,
  kisla: S.BARRACKS,
  kunye: S.DOGTAG,
  duduk: S.WHISTLE,

  // Eşyalar
  telefon: S.TELEFON,
  tisort: S.TISORT,
  uniformaKatli: S.UNIFORMA_KATLI,
  pantolon: S.PANTOLON,
  pijama: S.PIJAMA_KATLI,
  botBoyasi: S.BOT_BOYASI,
  tabanlik: S.TABANLIK,
  pudra: S.PUDRA,
  trasCantasi: S.TRAS_CANTASI,
  camasirTorbasi: S.CAMASIR_TORBASI,
  kilit: S.KILIT,
  cuzdan: S.CUZDAN,
  kontor: S.KONTOR,
  sabun: S.SABUN,
  terlik: S.TERLIK,
  corap: S.CORAP,
  krem: S.KREM,
  kitap: S.KITAP,
  defter: S.DEFTER,
  tesbih: S.TESBIH,
  sigara: S.SIGARA,
  cakmak: S.CAKMAK,
  atistirmalik: S.ATISTIRMALIK,
  enerjiIcecegi: S.ENERJI_ICECEGI,
} satisfies Record<string, SpriteDef>;

export type SpriteKey = keyof typeof SPRITES;
export const sprite = (k: SpriteKey) => SPRITES[k];
